version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  # streamlit_app:
  #   # build:
  #   #   context: .
  #   #   dockerfile: Dockerfile
  #   image: vectorverse:0.1
  #   # platform: linux/amd64
  #   environment:
  #     - test=1
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - redis
  #     - elasticsearch
  #   volumes:
  #     - /Users/gmcjy/Documents/sourcecode/github/gpt4all/:/gpt/